# This file controls what config variables you want to be able to allow your users
# to set, as well as those you'll be able to access from within the application.
# 
# If you want to be able to access a string config[:site_title], for example:
#   
# site_title:
#   name: Site Title
#   type: string
#   default: My Site
#   
# 'name' is the name that appears in the edit form
# 
# 'type' can be 'string' for a text field, 'password' for a password field or 'text' for a text area
#   'type' defaults to 'string'
# 
# 'default' is the default value to use if there's no entry in the database. Otherwise, nil will be returned
# 
# Some Examples:
#   
site_title:
  name: Site Title
  default: My Site
  type: string
#   
# site_description:
#   name: Description for Google
#   default: Lots of Awesomeness Here
#   type: text
#   
# secret:
#   name: Secret Password for Accessing Secret Areas
#   default: secret
#   type: password

id_cat_assurance:
  name: Identifiant de la categorie de produit Assurance            # sets the edit label
  default: 0               # sets the default value
  type: integer             # coerces the value to an integer

id_cat_busaller:
  name: Identifiant de la categorie de produit Transport aller            # sets the edit label
  default: 0               # sets the default value
  type: integer             # coerces the value to an integer

id_cat_busretour:
  name: Identifiant de la categorie de produit Transport retour            # sets the edit label
  default: 0               # sets the default value
  type: integer             # coerces the value to an integer

id_pack:
  name: Identifiant de la categorie de produit Pack            # sets the edit label
  default: 0               # sets the default value
  type: integer             # coerces the value to an integer

secret_paiement:
  name: Salt hash paiement            # sets the edit label
  default: achanger               # sets the default value
  type: string             # coerces the value to an integer

g_analytics:
  name: id google analytics            # sets the edit label
  default: achanger               # sets the default value
  type: string   

mode_maintenance:
  name: passage du site en mod maintenance            # sets the edit label
  default: false             # sets the default value
  type: boolean             # coerces the value to an integer

# blocage de la création des commandes
commandes_possibles:
  name: possibilité de créer des commandes?
  default: true
  type: boolean

# blocage de l'édition des commandes
commandes_editables:
  name: possibilité de modifier les commandes?
  default: true
  type: boolean

# date des paiements
echeances_paiement1:
  name: echeance des paiements  1          # sets the edit label
  default:             # sets the default value
  type: date
echeances_paiement2:
  name: echeance des paiements 2           # sets the edit label
  default:             # sets the default value
  type: date
echeances_paiement3:
  name: echeance des paiements 3           # sets the edit label
  default:             # sets the default value
  type: date

export__commande_pool_size:
  name: Nombre d'éléments dans un export de commande
  default: 100
  type: integer

facture_visible:
  name: bouton facture visible           # sets the edit label
  default: false             # sets the default value
  type: boolean  

serveur_mail:
  name: serveur mail           # sets the edit label
  default: ip             # sets the default value
  type: string

sender_mail:
  name: sender mail           # sets the edit label
  default: test@test.fr            # sets the default value
  type: string

max_commamdes_payables:
  name: nombre maxi de commandes qu'on peut payer           # sets the edit label
  default: 1360            # sets the default value
  type: integer  

type_resids:
  name: type resids
  default: Calme Anim's
  type: string

choix_chambre:
  name: Activer le choix des chambres pour les utilisateurs
  default: false
  type: boolean

display_button_type_residence:
  name: Afficher le bouton de choix du type de résidence
  default: false
  type: boolean

limite_inscription:
  name: "Seuil limite d'inscription des gens avant qu'ils ne soient mis en liste d'attente"
  default: 1360
  type: integer
  
option_limite_inscription:
  name: "Option pour limiter l'inscription"
  default: false            # sets the default value
  type: boolean
  
modification_options:
  name: Possibilité de modifier les options
  default: false
  type: boolean

ski_commandes:
  name: Ski commandés
  default: 'non'
  type: string

super_option_commandee:
  name: Super option commandée
  default: 'non'
  type: string

